---
# tasks file for nginx

- name: Install Nginx
  apt:
    name: "{{ nginx_package }}"
    state: present
  become: true

- name: Ensure Nginx is running and enabled on boot
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes
  become: true

- name: Deploy main Nginx configuration
  template:
    src: "{{ nginx_conf_template_path }}"
    dest: "{{ nginx_conf_path }}"
  notify: reload nginx
  become: true

- name: Deploy default site configuration
  template:
    src: "{{ nginx_default_template_path }}"
    dest: "{{ nginx_default_site_src }}"
  notify: reload nginx
  become: true

- name: Ensure default site is enabled
  file:
    src: "{{ nginx_default_site_src }}"
    dest: "{{ nginx_default_site_dest }}"
    state: link
  notify: reload nginx
  become: true
