---
# tasks file for nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Ensure Nginx is running and enabled on boot
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Deploy main Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: true

- name: Deploy default site configuration
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  become: true

- name: Ensure default site is enabled
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
  become: true
