galaxy_info:
  author: Krivosheev Svyatoslav
  description: Role that installs docker
  company: ITMO
  license: MIT

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - docker
    - container
    - linux

dependencies: []
